%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: /Users/tiantianxie/Documents/PHD2/CMSC636/hw4/data2ehrSample.xlsx
%    Worksheet: Sheet0
%
% To extend the code for use with different selected data or a different
% spreadsheet, generate a function instead of a script.

% Auto-generated by MATLAB on 2016/10/29 09:28:36

%% Import the data
[~, ~, raw] = xlsread('/Users/tiantianxie/Documents/PHD2/CMSC636/hw4/data2ehrSample.xlsx','Sheet0');
raw = raw(:,[1,6,10,15,17:end]);
raw(cellfun(@(x) ~isempty(x) && isnumeric(x) && isnan(x),raw)) = {''};

%% Replace non-numeric cells with NaN
R = cellfun(@(x) ~isnumeric(x) && ~islogical(x),raw); % Find non-numeric cells
raw(R) = {NaN}; % Replace non-numeric cells

%% Create output variable
data = reshape([raw{:}],size(raw));

%% Allocate imported array to column variable names
PatientID = data(:,1);
Days_From1stTBI = data(:,2);
Encounter_date = data(:,3);
TBI_encounter_flag = data(:,4);
PRE_max_days = data(:,5);
POST_max_days = data(:,6);

Stress = data(:,7);
PTSD = data(:,8);
Speech = data(:,9);
Anxiety = data(:,10);
Depression = data(:,11);
Headache = data(:,12);
Sleep = data(:,13);
Audiology = data(:,14);
Vision = data(:,15);
Neurologic = data(:,16);
Alzheimer = data(:,17);
Cognitive = data(:,18);
PCS = data(:,19);
Endocrine = data(:,20);
Skull_inj = data(:,21);
NON_skull_inj = data(:,22);

TBI_tag=[Stress PTSD Speech Anxiety Depression Headache Sleep Audiology Vision Neurologic Alzheimer Cognitive PCS Endocrine Skull_inj NON_skull_inj];
TBI_all=[PatientID Days_From1stTBI Encounter_date TBI_encounter_flag PRE_max_days POST_max_days TBI_tag];

TBI_all(1,:)=[];
%% Clear temporary variables
clearvars data raw R;